"""
Format an IronLayer plan as a GitHub PR comment (Markdown).

Usage:
    python format_comment.py \
        --status success|empty|failed \
        --plan-json /path/to/plan.json \
        --base-sha abc123 \
        --head-sha def456 \
        --error "optional error message" \
        --output /path/to/comment.md
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


FOOTER = "\n---\n*Generated by [IronLayer](https://ironlayer.app)*"


def format_failed(error: str, base_sha: str, head_sha: str) -> str:
    lines = [
        "## :rotating_light: IronLayer Plan",
        "",
        f"`{base_sha[:12]}` :arrow_right: `{head_sha[:12]}`",
        "",
        "**Plan generation failed.**",
        "",
    ]
    if error.strip():
        lines += [
            "<details>",
            "<summary>Error details</summary>",
            "",
            "```",
            error.strip(),
            "```",
            "",
            "</details>",
        ]
    lines.append(FOOTER)
    return "\n".join(lines)


def format_empty(base_sha: str, head_sha: str) -> str:
    lines = [
        "## :white_check_mark: IronLayer Plan",
        "",
        f"`{base_sha[:12]}` :arrow_right: `{head_sha[:12]}`",
        "",
        "**No model changes detected.** Nothing to execute.",
        FOOTER,
    ]
    return "\n".join(lines)


def format_success(plan: dict, base_sha: str, head_sha: str) -> str:
    summary = plan.get("summary", {})
    steps = plan.get("steps", [])
    plan_id = plan.get("plan_id", "unknown")

    total_steps = summary.get("total_steps", len(steps))
    estimated_cost = summary.get("estimated_cost_usd", 0)
    models_changed = summary.get("models_changed", [])
    cosmetic_skipped = summary.get("cosmetic_changes_skipped", [])
    contract_violations_count = summary.get("contract_violations_count", 0)
    breaking_count = summary.get("breaking_contract_violations", 0)

    # Header
    if breaking_count > 0:
        icon = ":warning:"
    else:
        icon = ":hammer_and_wrench:"

    lines = [
        f"## {icon} IronLayer Plan",
        "",
        f"`{base_sha[:12]}` :arrow_right: `{head_sha[:12]}` &nbsp; | "
        f"&nbsp; **{total_steps} step{'s' if total_steps != 1 else ''}** &nbsp; | "
        f"&nbsp; Est. **${estimated_cost:.2f}**",
        "",
    ]

    # Breaking contract violations banner
    if breaking_count > 0:
        lines += [
            f"> :rotating_light: **{breaking_count} breaking contract "
            f"violation{'s' if breaking_count != 1 else ''}** detected. "
            "Review before merging.",
            "",
        ]

    # Steps table
    if steps:
        lines += [
            "### Execution Steps",
            "",
            "| # | Model | Run Type | Reason | Cost |",
            "|--:|-------|----------|--------|-----:|",
        ]
        for i, step in enumerate(steps, 1):
            model = step.get("model", "unknown")
            run_type = step.get("run_type", "UNKNOWN")
            reason = step.get("reason", "")
            cost = step.get("estimated_cost_usd", 0)

            # Truncate long reasons
            if len(reason) > 60:
                reason = reason[:57] + "..."

            run_badge = ":arrows_counterclockwise:" if run_type == "INCREMENTAL" else ":arrow_right:"
            lines.append(
                f"| {i} | `{model}` | {run_badge} {run_type} | {reason} | ${cost:.2f} |"
            )
        lines.append("")

    # Contract violations
    all_violations = []
    for step in steps:
        for v in step.get("contract_violations", []):
            all_violations.append({"model": step.get("model", "unknown"), **v})

    if all_violations:
        lines += [
            "<details>",
            f"<summary>:clipboard: Contract Violations ({len(all_violations)})</summary>",
            "",
            "| Model | Column | Type | Severity | Message |",
            "|-------|--------|------|----------|---------|",
        ]
        for v in all_violations:
            severity = v.get("severity", "INFO")
            sev_icon = {
                "BREAKING": ":red_circle:",
                "WARNING": ":yellow_circle:",
                "INFO": ":blue_circle:",
            }.get(severity, ":white_circle:")
            lines.append(
                f"| `{v['model']}` | `{v.get('column_name', '-')}` | "
                f"{v.get('violation_type', '-')} | {sev_icon} {severity} | "
                f"{v.get('message', '-')} |"
            )
        lines += ["", "</details>", ""]

    # Cosmetic changes skipped
    if cosmetic_skipped:
        lines += [
            "<details>",
            f"<summary>:fast_forward: Cosmetic changes skipped ({len(cosmetic_skipped)})</summary>",
            "",
            "These models had whitespace/comment-only changes and do not require re-execution:",
            "",
        ]
        for m in cosmetic_skipped:
            lines.append(f"- `{m}`")
        lines += ["", "</details>", ""]

    # Full plan JSON
    if steps:
        plan_json_compact = json.dumps(plan, indent=2, sort_keys=True)
        lines += [
            "<details>",
            "<summary>:page_facing_up: Full plan JSON</summary>",
            "",
            "```json",
            plan_json_compact,
            "```",
            "",
            "</details>",
            "",
        ]

    # Plan ID
    lines.append(f"<sub>Plan ID: `{plan_id[:16]}`</sub>")
    lines.append(FOOTER)

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Format IronLayer plan as PR comment")
    parser.add_argument("--status", required=True, choices=["success", "empty", "failed"])
    parser.add_argument("--plan-json", required=True, help="Path to plan.json")
    parser.add_argument("--base-sha", required=True)
    parser.add_argument("--head-sha", required=True)
    parser.add_argument("--error", default="")
    parser.add_argument("--output", required=True, help="Output markdown file path")
    args = parser.parse_args()

    if args.status == "failed":
        md = format_failed(args.error, args.base_sha, args.head_sha)
    elif args.status == "empty":
        md = format_empty(args.base_sha, args.head_sha)
    else:
        plan_path = Path(args.plan_json)
        if not plan_path.exists():
            md = format_empty(args.base_sha, args.head_sha)
        else:
            plan = json.loads(plan_path.read_text())
            steps = plan.get("steps", [])
            if not steps:
                md = format_empty(args.base_sha, args.head_sha)
            else:
                md = format_success(plan, args.base_sha, args.head_sha)

    Path(args.output).write_text(md)
    print(f"Comment written to {args.output} ({len(md)} bytes)")


if __name__ == "__main__":
    main()
